config/routes.rb
Twitter::Application.routes.draw do
  devise_for :users
  as :user do
    get 'user/signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'my_following'=>'users#my_following',:as=>:my_following   
    
  end
  root :to=> "homes#index"

  resources :tweets do
    member do
      post :retweet      
    end
  end
  match ':name' => 'users#profile',:as=>:my_profile

  match ':controller(/:action(/:id))(.:format)'
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :text,:user_id
  # validates :text,:length=>{ maximum: 140 }
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
 validates :name,:presence=>true
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:name
  # attr_accessible :title, :body
 has_many :tweets
 has_many :relationships, foreign_key: "follower_id", dependent: :destroy
 has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
 has_many :followed_users, through: :relationships, source: :followed
 
 def to_param
  name
 end
  def following?(other_user)       
      return true unless self.relationships.where(followed_id: other_user.id).blank?
  end

  # def follow!(other_user)
    # self.relationships.create!(followed_id: other_user.id)
  # end

  def unfollow!(other_user)
    self.relationships.where(followed_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def login_required
    unless current_user
      redirect_to new_user_session_path
    end
  end
  def all_user
    @all_users=User.all-[current_user]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    if current_user
     redirect_to  "/#{current_user.name}"
    else
     redirect_to new_user_session_path
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    @tweet=Tweet.new params[:tweet]
   unless @tweet.save
     flash[:error]=@tweet.errors.messages
   end
    redirect_to root_path
    puts @tweet.errors.messages
  end
  def retweet
    tweet=Tweet.find params[:id]
    
    unless current_user.tweets.create(:text=>tweet.text)
     flash[:error]=current_user.tweets.create(:text=>tweet.text).errors.messages
   end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_filter :login_required,:all_user
   
   def profile
     @user = User.find_by_name(params[:name])
     @followers=@user.followed_users
     # User.find_by_username(params[:id])
     @tweet=@user.tweets.new     
   end
   
   def my_following
     follwing_user=User.find params[:id]   
     current_user.relationships.create!(followed_id: follwing_user.id) 
     redirect_to root_path
   end
   
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html>

app/views/users/_user_tweets.html.erb
<%unless current_user.tweets.blank?%>
  <%current_user.tweets.each do |t|%>
     <%=t.text%><%=link_to "retweet", retweet_tweet_path(t.id),:method=>"POST"%>
  <%end%>
<%end%>

app/views/users/profile.html.erb
<p>Hi This is <%=current_user.email%></p> 
  <div style="width: 40px;">
   <%=form_for @tweet do |f|%>
   <%=f.label "Tweet"%><br />
   <%=f.hidden_field :user_id%>   
   <%=f.text_area :text,:cols => 50, :rows => 5%>   
   <%=f.submit "Post",:id=>"post_tweet",:disable=>false%>
   <%end%>
   <div>
   <span>Tweets</span><br />
       <%=current_user.tweets.count%>  
       <br />
       </div>
   <div>
   	
   <span>Follwings</span><br />
       <%=current_user.followed_users.count%>  
       <br />
    </div>&nbsp;
     <div>
   <span>Followers</span><br />
       <%=current_user.reverse_relationships.count%>  
       <br />
       </div>
       </div>
       <div style="width: 60px;">
       	<%=render 'user_tweets'%>
       </div>
<%if current_user%>
<%=link_to "Logout",destroy_user_session_path,:method=>'delete'%>

<%end%>


<div align="right">
	To Follows<br />
	

	<%unless @all_users.blank?%>
	<ul>
	<%@all_users.each do |u|%>	
	<%unless current_user.following?(u)%>
	<li><%=u.email%><a href="<%=my_following_path(:id=>u.id)%>">Follow Me</a></li>
	<%end%> 
	<%end%>
	</ul>
	<%end%>
</div>